// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWA3u26AvRIo-AO-AV58FjUDW1HcquCkE',
    appId: '1:453456656699:android:f3d747df8a6735d63e9f1e',
    messagingSenderId: '453456656699',
    projectId: 'zenrun-b3061',
    storageBucket: 'zenrun-b3061.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCLNsiH5edNK2uXzMwN-cN7DP4ceX1tA',
    appId: '1:453456656699:web:9d43be338d7ce2553e9f1e',
    messagingSenderId: '453456656699',
    projectId: 'zenrun-b3061',
    authDomain: 'zenrun-b3061.firebaseapp.com',
    storageBucket: 'zenrun-b3061.firebasestorage.app',
    measurementId: 'G-T0TWBF2Y8C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZG1ZMtivoPKvPxy6dU18E988Y50CTANQ',
    appId: '1:453456656699:ios:ffeaccb02a2884d63e9f1e',
    messagingSenderId: '453456656699',
    projectId: 'zenrun-b3061',
    storageBucket: 'zenrun-b3061.firebasestorage.app',
    iosBundleId: 'com.tivasoft.zenrunapps',
  );

}